# Generated by Django 4.0.1 on 2022-12-06 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_paymentmethod_profile_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_num',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
