# Generated by Django 4.0.1 on 2022-11-19 22:05

import Subscriptions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Studios', '0005_rename_longtitude_studio_longitude_alter_image_image'),
        ('Accounts', '0006_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[Subscriptions.models._validate_price])),
                ('time_unit', models.CharField(choices=[('DAY', 'day'), ('WEEK', 'week'), ('MON', 'month'), ('YEAR', 'year')], max_length=4)),
                ('time_range', models.IntegerField(blank=True, default=1, validators=[Subscriptions.models._validate_time_range])),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='Studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('canceled', models.BooleanField(blank=True, default=False)),
                ('auto_pay', models.BooleanField(blank=True, default=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='Subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='Accounts.profile')),
            ],
        ),
    ]
