# Generated by Django 4.0.1 on 2022-11-22 02:01

import Subscriptions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0007_paymentmethod_profile_is_subscribed_and_more'),
        ('Studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[Subscriptions.models._validate_price])),
                ('time_unit', models.CharField(choices=[('DAY', 'day'), ('WEEK', 'week'), ('MON', 'month'), ('YEAR', 'year')], max_length=4)),
                ('time_range', models.IntegerField(blank=True, default=1, validators=[Subscriptions.models._validate_time_range])),
                ('currency', models.CharField(choices=[('CAD', 'cad'), ('USD', 'usd')], default='CAD', max_length=3)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='Studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('canceled', models.BooleanField(blank=True, default=False)),
                ('auto_pay', models.BooleanField(blank=True, default=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='Subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='Accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_method', to='Accounts.paymentmethod')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
