# Generated by Django 4.0.1 on 2022-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_remove_plan_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
