# Generated by Django 4.0.1 on 2022-11-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0004_payment_subscription_alter_payment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
