# Generated by Django 4.0.1 on 2022-12-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_enrollment_in_future'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinstance',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
