# Generated by Django 4.0.1 on 2022-11-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Studios', '0005_rename_longtitude_studio_longitude_alter_image_image'),
        ('classes', '0004_alter_class_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Studios.studio'),
        ),
    ]
