# Generated by Django 4.0.1 on 2022-11-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_class_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='categories',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_full', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_date', models.DateField()),
                ('belonged_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_instances', to='classes.class')),
            ],
        ),
    ]
