# Generated by Django 4.0.1 on 2022-11-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_class_categories_classinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='classinstance',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
