# Generated by Django 4.0.1 on 2022-11-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_delete_category_classinstance_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstance',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
