# Generated by Django 4.0.1 on 2022-11-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='class_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
