# Generated by Django 4.0.1 on 2022-11-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_enrollment_class_start_time_enrollment_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='class_start_time',
            field=models.DateTimeField(),
        ),
    ]
