# Generated by Django 4.0.1 on 2022-11-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_alter_enrollment_class_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstance',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='classinstance',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
