# Generated by Django 4.0.1 on 2022-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=43.6629, max_digits=8),
        ),
        migrations.AddField(
            model_name='studio',
            name='longtitude',
            field=models.DecimalField(decimal_places=3, default=79.3957, max_digits=8),
        ),
    ]
