# Generated by Django 4.0.1 on 2022-11-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studios', '0002_studio_latitude_studio_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=43.6629, max_digits=9),
        ),
        migrations.AlterField(
            model_name='studio',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, default=79.3957, max_digits=9),
        ),
    ]
