# Generated by Django 4.0.1 on 2022-11-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studios', '0003_alter_studio_latitude_alter_studio_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='studio',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
