# Generated by Django 4.0.1 on 2022-11-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studios', '0004_alter_studio_latitude_alter_studio_longtitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='studio_images/'),
        ),
    ]
